### ISSUE TITLE
feat: @PreUpdate/@PrePersist

### ISSUE THREAD

**Issue by julianobrasil** [alisson-gomesc/jkniv#1]
I would be nice if we had `@PreUpdate`/`@PrePersist` annotations.

**Comment by julianobrasil** [comment]
Good to know. I'm using Couchdb. I'll let this issue opened for now so you can track an eventual development of this feature for the mentioned technologies. But feel free to close it for now if you want to.

**Comment by julianobrasil** [comment]
Oh, I've just realized that you've labeled this one as an enhancement. 😃

**Comment by alisson-gomesc** [comment]
First implementation was released for 0.6.0.M43

http://jkniv.sourceforge.net/jkniv-whinstone-couchdb/callback-methods.html
